import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/Sidebar"
import { LogOutIcon } from "lucide-react";
import { LayoutDropdown } from "@/components/layout-dropdown";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased debug-screens bg-slate-50`}
      >
        <div className="flex w-full justify-between items-center py-4 px-6">
          <p>MyCompany</p>
          <div className="flex">
            <LayoutDropdown />
          </div>
        </div>

        <div className="min-h-screen w-ful text-black flex px-6">
          <Sidebar />
          <div className="w-full p-8">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
